### ISSUE TITLE
Auto adjust height of the row 

### ISSUE THREAD

**Issue by Abdulrehmanharisdev** [walkframe/gridsheet#57]
### Description

is there any way  to adjust the row height automaticly according to content of the cell?

**Comment by righ** [comment]
Thank you for your comment.

There is no option that automatically adjusts the height, but this may be achieved by using options.onSave.
Since onSave accepts (table, position), you can get `{[address]: Cell}` by writing the following.
```js
const diff = table.getObjectFlatten({
  filter: (cell) =>
    ! !cell?.changedAt &&
    cell.changedAt > table.lastChangedAt!
});
```
For example, you could get the number of rows from `Cell.value` and multiply by line-height to determine the height.
Or you could get the HTML height by identifying the HTML element `td[data-address="${address}"] .gs-cell-rendered` from position.
This might be applied like `table.update({diff: {[y]: {height}}, partial: true})` to change the height.

Please give it a try.
