### ISSUE TITLE
Issue : Cell Border color issue

### ISSUE THREAD

**Issue by Abdulrehmanharisdev** [walkframe/gridsheet#66]
When the table renders for the first time, the cell border colors display correctly. However, after selecting a cell and then moving the focus to another cell, the border color of the previously selected cell disappears and turns gray.

![image](https://github.com/user-attachments/assets/8b439fbd-09dd-45ce-85b0-0424c6134fe0)

Now border color fades away
![image](https://github.com/user-attachments/assets/249435b2-3df0-452c-8707-4212ba3485a7)

**Comment by righ** [comment]
In conclusion, try setting the style for each side as follows
https://github.com/walkframe/gridsheet/blob/master/.storybook/examples/basic/style.stories.tsx#L72-L77

You are probably applying the style to a shorthand property that groups the four sides together, like `borderColor: “red”`.
If so, the JS console will tell you `Warning: Removing a style property during rerender (borderRight) when a conflicting property is set (border) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values. `.
I assume that because gridsheet applies the cell selection border style to each edge, it conflicts with the style you specified for all edges and is therefore discarded.

For an explanation of the shorthand property, see
https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties
