### ISSUE TITLE
^1.1.0 version Cells not aligning in sheet (left,center,right)

### ISSUE THREAD

**Issue by haseebmanzoorcbt** [walkframe/gridsheet#68]
### Description

I upgraded from 1.0.7 version where there was an issue in typing (had to press button several times to type) to latest one 1.1.0 

After upgrade npm package version, the alignment in editor is no more working and being applied i am setting these properties for cells in sheet

 {
          alignItems: alignment,
            justifyContent: alignment,
          },
          
          

### Reproduction URL

https://github.com/haseebmanzoorcbt

### Reproduction steps

```bash
1
```

### Version

1.1.0

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by righ** [comment]
Thank you for reporting the bug. I have identified the issue where justifyContent stops working. The cause is the commit d41c4789b27316cc1329ceded466731d452fa73a, which was made to fix the bug where the background color was not applied in Safari. Please check the release of 1.1.1-alpha.1 for the fix.
